CREATE TABLE GC_AREA_COMUM (
    ARE_COD SERIAL PRIMARY KEY,
    CON_COD INTEGER NOT NULL REFERENCES GC_CONDOMINIO(CON_COD),
    ARE_NOME VARCHAR(100) NOT NULL,
    ARE_DESCRICAO TEXT,
    ARE_TERMOS_USO TEXT,
    ARE_CAPACIDADE_MAXIMA INTEGER,
    ARE_PERMITE_CONVIDADOS BOOLEAN DEFAULT FALSE,
    ARE_LIMITE_CONVIDADOS INTEGER,
    ARE_DIAS_ANTECEDENCIA_MIN INTEGER DEFAULT 1,
    ARE_DIAS_ANTECEDENCIA_MAX INTEGER DEFAULT 30,
    ARE_ATIVA BOOLEAN DEFAULT TRUE,
    ARE_TAXA_VALOR NUMERIC(10,2),
    ARE_DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ARE_DT_ATUALIZACAO TIMESTAMP
);

CREATE TABLE GC_AREA_COMUM_TURNO (
    TUR_COD SERIAL PRIMARY KEY,
    ARE_COD INTEGER NOT NULL REFERENCES GC_AREA_COMUM(ARE_COD) ON DELETE CASCADE,
    TUR_NOME VARCHAR(50) NOT NULL,
    TUR_HORA_INICIO TIME NOT NULL,
    TUR_HORA_FIM TIME NOT NULL,
    TUR_ATIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE GC_RESERVA (
    RES_COD SERIAL PRIMARY KEY,
    ARE_COD INTEGER NOT NULL REFERENCES GC_AREA_COMUM(ARE_COD),
    TUR_COD INTEGER REFERENCES GC_AREA_COMUM_TURNO(TUR_COD),
    UNI_COD INTEGER NOT NULL REFERENCES GC_UNIDADE(UNI_COD),
    PES_COD_MORADOR INTEGER NOT NULL REFERENCES GC_PESSOA(PES_COD),
    PES_COD_APROVADOR INTEGER REFERENCES GC_PESSOA(PES_COD),
    RES_DATA DATE NOT NULL,
    RES_STATUS VARCHAR(30) NOT NULL,
    RES_TERMOS_ACEITOS BOOLEAN NOT NULL DEFAULT FALSE,
    RES_MOTIVO_REJEICAO TEXT,
    RES_DT_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RES_DT_ATUALIZACAO TIMESTAMP
);

CREATE TABLE GC_RESERVA_CONVIDADO (
    RCV_COD SERIAL PRIMARY KEY,
    RES_COD INTEGER NOT NULL REFERENCES GC_RESERVA(RES_COD) ON DELETE CASCADE,
    RCV_NOME VARCHAR(150) NOT NULL,
    RCV_DOCUMENTO VARCHAR(50)
);