

CREATE TABLE GC_PESSOA (
PES_COD INT IDENTITY (1,1),
PES_NOME VARCHAR(100) NOT NULL,
PES_CPF_CNPJ VARCHAR(14) UNIQUE NOT NULL,
PES_TIPO CHAR(1) DEFAULT('F'), /*F OU J*/
PES_EMAIL VARCHAR(100) UNIQUE NOT NULL,
PES_TELEFONE VARCHAR (20),
PES_TELEFONE2 VARCHAR (20),
PES_ATIVO BIT DEFAULT 1, /*1 para True (ativo), 0 para False (inativo)*/
PES_DT_CADASTRO DATETIME DEFAULT GETDATE(),
PES_DT_ATUALIZACAO DATETIME

PRIMARY KEY (PES_COD)
)

CREATE TABLE GC_ADMINISTRADORA (
ADM_COD INT IDENTITY (1,1),
PES_COD INT NOT NULL,
ADM_RESPONSAVEL INT NOT NULL

PRIMARY KEY (ADM_COD),
FOREIGN KEY (PES_COD) REFERENCES GC_PESSOA (PES_COD),
FOREIGN KEY (ADM_RESPONSAVEL) REFERENCES GC_PESSOA (PES_COD)
)


CREATE TABLE GC_CONDOMINIO (
CON_COD INT IDENTITY (1,1),
CON_NOME VARCHAR(100) NOT NULL,
/*ENDEREÇO*/
	CON_LOGRADOURO VARCHAR(100),
    CON_NUMERO VARCHAR(10),
    CON_COMPLEMENTO VARCHAR(50),
    CON_BAIRRO VARCHAR(50),
    CON_CIDADE VARCHAR(50),
    CON_ESTADO CHAR(2),  
    CON_CEP CHAR(8),
    CON_PAIS VARCHAR(50) DEFAULT 'Brasil',
    CON_REFERENCIA VARCHAR(100),
CON_NUMERO_UNIDADES INT,
CON_TIPOLOGIA CHAR(1),
CON_DT_VENCIMENTO_TAXA INT,
ADM_COD INT,
CON_DT_CADASTRO DATETIME DEFAULT GETDATE(),
CON_DT_ATUALIZACAO DATETIME,
PRIMARY KEY (CON_COD),
FOREIGN KEY (ADM_COD) REFERENCES GC_ADMINISTRADORA (ADM_COD)
)



CREATE TABLE GC_UNIDADE (
UNI_COD INT IDENTITY (1,1),
UNI_STATUS_OCUPACAO CHAR(1), /* O - OCUPADO, D - DESOCUPADO, V - EM VENDA, A - ALUGADO*/
UNI_NUMERO VARCHAR(10) NOT NULL,
CON_COD INT NOT NULL,
UNI_DT_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
UNI_DT_ATUALIZACAO DATETIME,
PRIMARY KEY (UNI_COD),
FOREIGN KEY (CON_COD) REFERENCES GC_CONDOMINIO (CON_COD)
)


CREATE TABLE GC_MORADOR (
MOR_COD INT IDENTITY (1,1),
PES_COD INT NOT NULL,
UNI_COD INT NOT NULL,
MOR_TIPO_RELACIONAMENTO CHAR(1) NOT NULL, /* P - 'PROPRIETARIO', I - 'INQUILINO', C - 'CONJUGE', D - 'DEPENDENTE'*/
MOR_DT_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
MOR_DT_ATUALIZACAO DATETIME,
PRIMARY KEY (MOR_COD),
FOREIGN KEY (PES_COD) REFERENCES GC_PESSOA (PES_COD),
FOREIGN KEY (UNI_COD) REFERENCES GC_UNIDADE (UNI_COD),
UNIQUE (PES_COD, UNI_COD)


)



CREATE TABLE GC_TIPO_COBRANCA (
TIC_COD INT IDENTITY (1,1),
TIC_DESCRICAO VARCHAR(100) NOT NULL,
TIC_DT_CADASTRO DATETIME DEFAULT GETDATE(),
TIC_DT_ATUALIZACAO DATETIME,
PRIMARY KEY (TIC_COD)
)



CREATE TABLE GC_FINANCEIRO_COBRANCA (
FIC_COD INT IDENTITY (1,1),
UNI_COD INT NOT NULL,
FIC_VALOR_TAXA DECIMAL(10, 2) NOT NULL,
FIC_DT_VENCIMENTO DATE NOT NULL,
FIC_DT_PAGAMENTO DATE,
TIC_COD INT NOT NULL,
FIC_VALOR_PAGO DECIMAL(10, 2),
FIC_DT_CADASTRO DATETIME DEFAULT GETDATE(),
FIC_DT_ATUALIZACAO DATETIME,
FIC_STATUS_PAGAMENTO VARCHAR(30) NOT NULL DEFAULT 'A_VENCER',

PRIMARY KEY (FIC_COD),
FOREIGN KEY (UNI_COD) REFERENCES GC_UNIDADE (UNI_COD),
FOREIGN KEY (TIC_COD) REFERENCES GC_TIPO_COBRANCA(TIC_COD) 

)


CREATE TABLE GC_GESTAO_COMUNICACAO(
COM_COD INT IDENTITY (1, 1),
CON_COD INT NOT NULL,
COM_REMETENTE INT NOT NULL,
COM_DES_TODOS CHAR(1) DEFAULT ('N'),
COM_ASSUNTO VARCHAR(50) NOT NULL,
COM_MENSAGEM VARCHAR(500) NOT NULL,
COM_TIPO_NOTIFICACAO CHAR(1), /*P - PUSH, E - e-mail*/
COM_DT_CADASTRO DATETIME DEFAULT GETDATE() NOT NULL,
COM_DT_ATUALIZACAO DATETIME,
COM_DT_ENVIO DATETIME NULL,

PRIMARY KEY(COM_COD),
FOREIGN KEY (CON_COD) REFERENCES GC_CONDOMINIO (CON_COD),
FOREIGN KEY (COM_REMETENTE) REFERENCES GC_PESSOA(PES_COD)
)



CREATE TABLE GC_COMUNICADO_ENTREGA (
    CME_COD INT IDENTITY(1,1),
    COM_COD INT NOT NULL,                          
    PES_COD INT NOT NULL,                          
    CME_STATUS_LEITURA BIT DEFAULT 0 NOT NULL,     -- 0 para não lido, 1 para lido
    CME_DT_LEITURA DATETIME NULL,
    CME_STATUS_ENVIO VARCHAR(20) DEFAULT 'PENDENTE' NOT NULL, -- Ex: 'PENDENTE', 'ENVIADO', 'FALHOU'
    CME_DT_ENVIO_INDIVIDUAL DATETIME NULL,           -- Data que foi efetivamente enviado para este destinatário

    PRIMARY KEY (CME_COD),
    UNIQUE (COM_COD, PES_COD), 
    FOREIGN KEY (COM_COD) REFERENCES GC_GESTAO_COMUNICACAO(COM_COD),
    FOREIGN KEY (PES_COD) REFERENCES GC_PESSOA(PES_COD)
)


CREATE TABLE GC_ASSEMBLEIA (
ASS_COD INT IDENTITY,
ASS_ATA VARCHAR(500) NULL, --ARQUIVO
ASS_DESCRICAO VARCHAR(100) NOT NULL,
ASS_DATA_HORA DATETIME NOT NULL,
ASS_STATUS VARCHAR(20) NOT NULL DEFAULT 'A', -- A- AGENDADA, F- FINALIZADA, C - CANCELADA,
ASS_DT_CADASTRO DATETIME DEFAULT GETDATE(),
ASS_DT_ATUALIZACAO DATETIME,
CON_COD INT NOT NULL,  

PRIMARY KEY (ASS_COD),
FOREIGN KEY (CON_COD) REFERENCES GC_CONDOMINIO (CON_COD)

)

CREATE TABLE GC_ASSEMBLEIA_TOPICO(
ASP_COD INT IDENTITY,
ASP_DESCRICAO VARCHAR(100) NOT NULL,
ASS_COD INT NOT NULL,

PRIMARY KEY (ASP_COD),
FOREIGN KEY (ASS_COD) REFERENCES GC_ASSEMBLEIA (ASS_COD)

)


CREATE TABLE GC_ASSEMBLEIA_PARTICIPANTE(
ASS_COD INT,
PES_COD INT,
ASP_PARTICIPACAO BIT DEFAULT 0, /*0 - NÃO CONFIRMADA 1 - CONFIRMADA*/

PRIMARY KEY (ASS_COD, PES_COD),
FOREIGN KEY (ASS_COD) REFERENCES GC_ASSEMBLEIA (ASS_COD),
FOREIGN KEY (PES_COD) REFERENCES GC_PESSOA(PES_COD)

)

CREATE TABLE GC_ASSEMBLEIA_VOTO (
ASP_COD INT,
PES_COD INT,
ASV_VOTO CHAR(1) , /*S para SIM - N para NÃO - A para ABSTENÇÃO*/

PRIMARY KEY (ASP_COD, PES_COD),
FOREIGN KEY (PES_COD) REFERENCES GC_PESSOA(PES_COD),
FOREIGN KEY (ASP_COD) REFERENCES GC_ASSEMBLEIA_TOPICO (ASP_COD)


)



CREATE TABLE GC_AREA_COMUM (
    ARC_COD INT IDENTITY(1,1),
    CON_COD INT NOT NULL,                       
    ARC_NOME VARCHAR(100) NOT NULL,             
    ARC_DESCRICAO VARCHAR(500),                 
    ARC_REGRAS_USO TEXT,                        
    ARC_CAPACIDADE_MAXIMA INT,                 
    ARC_PERMITE_RESERVA BIT DEFAULT 1 NOT NULL, -- Flag para habilitar/desabilitar reservas para esta área
    ARC_DT_CADASTRO DATETIME DEFAULT GETDATE(),
    ARC_DT_ATUALIZACAO DATETIME,

    PRIMARY KEY (ARC_COD),
    FOREIGN KEY (CON_COD) REFERENCES GC_CONDOMINIO (CON_COD)
)


CREATE TABLE GC_RESERVA_AREA_COMUM (
    RAC_COD INT IDENTITY(1,1),
    ARC_COD INT NOT NULL,                       
    UNI_COD INT NOT NULL,                       
    PES_COD_SOLICITANTE INT NOT NULL,           
    RAC_DATA_HORA_INICIO DATETIME NOT NULL,    
    RAC_DATA_HORA_FIM DATETIME NOT NULL,        
    RAC_STATUS VARCHAR(20) NOT NULL DEFAULT 'SOLICITADA', -- Ex: 'SOLICITADA', 'CONFIRMADA', 'CANCELADA', 'REALIZADA'
    RAC_OBSERVACOES VARCHAR(500),
    RAC_DT_SOLICITACAO DATETIME DEFAULT GETDATE(),
    RAC_DT_ATUALIZACAO DATETIME,

    PRIMARY KEY (RAC_COD),
    FOREIGN KEY (ARC_COD) REFERENCES GC_AREA_COMUM (ARC_COD),
    FOREIGN KEY (UNI_COD) REFERENCES GC_UNIDADE (UNI_COD),
    FOREIGN KEY (PES_COD_SOLICITANTE) REFERENCES GC_PESSOA (PES_COD)
)


CREATE TABLE GC_SOLICITACAO_MANUTENCAO (
    SMA_COD INT IDENTITY(1,1),
    CON_COD INT NOT NULL,                       
    UNI_COD INT NULL,                           
    PES_COD_SOLICITANTE INT NOT NULL,         
    SMA_LOCAL_DESCRICAO VARCHAR(255),           
    SMA_CATEGORIA VARCHAR(50) NOT NULL,         
    SMA_DESCRICAO_PROBLEMA TEXT NOT NULL,       
    SMA_STATUS VARCHAR(30) NOT NULL DEFAULT 'ABERTA', -- Ex: 'ABERTA', 'EM_ANALISE', 'EM_EXECUCAO', 'CONCLUIDA', 'CANCELADA'
    PES_COD_RESPONSAVEL INT NULL,               -- FK para GC_PESSOA (funcionário/terceiro responsável pela execução)
    SMA_DT_ABERTURA DATETIME DEFAULT GETDATE(),
    SMA_DT_CONCLUSAO DATETIME NULL,
    SMA_DT_ATUALIZACAO DATETIME,

    PRIMARY KEY (SMA_COD),
    FOREIGN KEY (CON_COD) REFERENCES GC_CONDOMINIO (CON_COD),
    FOREIGN KEY (UNI_COD) REFERENCES GC_UNIDADE (UNI_COD),
    FOREIGN KEY (PES_COD_SOLICITANTE) REFERENCES GC_PESSOA (PES_COD),
    FOREIGN KEY (PES_COD_RESPONSAVEL) REFERENCES GC_PESSOA (PES_COD)
)


CREATE TABLE GC_USUARIO_CONDOMINIO (
    PES_COD INT NOT NULL,                        
    CON_COD INT NOT NULL,                        
    USC_PAPEL CHAR(1) NOT NULL,              -- Ex: S - 'SINDICO', M - 'MORADOR', F - 'FUNCIONARIO_ADM', P - 'PORTEIRO', A - ADM
    USC_DT_ASSOCIACAO DATETIME DEFAULT GETDATE() NOT NULL,
    USC_ATIVO_ASSOCIACAO BIT DEFAULT 1 NOT NULL, -- Permite desativar um papel sem apagar o registro

    -- Uma pessoa pode ter múltiplos papéis no mesmo condomínio 
    PRIMARY KEY (PES_COD, CON_COD, USC_PAPEL),
    FOREIGN KEY (PES_COD) REFERENCES GC_PESSOA (PES_COD),
    FOREIGN KEY (CON_COD) REFERENCES GC_CONDOMINIO (CON_COD)
)


CREATE TABLE GC_DOCUMENTO (
    DOC_COD INT IDENTITY(1,1),
    CON_COD INT NOT NULL,                       
    DOC_NOME VARCHAR(150) NOT NULL,             
    DOC_TIPO VARCHAR(50) NOT NULL,              
    DOC_CAMINHO_ARQUIVO VARCHAR(500) NOT NULL,  
    ASS_COD INT NULL,                           -- Opcional: link para a assembleia, se for uma ata
    PES_COD_UPLOAD INT NOT NULL,               
    DOC_PERMISSAO_VISUALIZAR CHAR(1) DEFAULT  'T' NOT NULL, -- T - TODOS, A - ADM, M - TODOS OS MORADORES , S - SELECIONADOS
    DOC_DT_UPLOAD DATETIME DEFAULT GETDATE(),
    DOC_DT_ATUALIZACAO DATETIME,

    PRIMARY KEY (DOC_COD),
    FOREIGN KEY (CON_COD) REFERENCES GC_CONDOMINIO (CON_COD),
    FOREIGN KEY (ASS_COD) REFERENCES GC_ASSEMBLEIA (ASS_COD),
    FOREIGN KEY (PES_COD_UPLOAD) REFERENCES GC_PESSOA (PES_COD)
)

CREATE TABLE DC_DOCUMENTO_PERMISSAO_VISUALIZAR(
DOC_COD INT,
PES_COD INT,

PRIMARY KEY (DOC_COD, PES_COD),
FOREIGN KEY (DOC_COD) REFERENCES GC_DOCUMENTO (DOC_COD),
FOREIGN KEY (PES_COD) REFERENCES GC_PESSOA (PES_COD)
)