# CONFIGURAÇÃO DE BANCO DE DADOS PARA DESENVOLVIMENTO LOCAL (SUPABASE)
# ===============================================
spring.datasource.url=jdbc:postgresql://ep-purple-term-acjze5q1-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_u9LoPlzphxn5
# ===============================================
# CONFIGURAÇÕES DO JPA/HIBERNATE (PARA DESENVOLVIMENTO)
# ===============================================
# 'update' é mais seguro para desenvolvimento. Ele cria ou atualiza as tabelas se necessário.
spring.jpa.hibernate.ddl-auto=update
# 'true' para vermos os comandos SQL no console durante o desenvolvimento.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================================
# DESATIVA O FLYWAY (PREVENÇÃO DE ERROS)
# ===============================================
spring.flyway.enabled=false

# ===============================================
# CONFIGURAÇÕES DE SEGURANÇA (JWT) (PARA DESENVOLVIMENTO)
# ===============================================
# Chave JWT que você forneceu.
api.security.jwt.secret-key=NzE3NjRBNUIyRDYxNTM3NzVENzI0NDJEN0E2MzU3NkM1QjMzNkI1ODU5MzI1MTZFNEM1MzZERDgxNEE3REQ1NA==
# Tempo de expiração do token em milissegundos (Ex: 1 hora = 3600000)
api.security.jwt.expiration-time-ms=3600000

# ===============================================
# CONFIGURAÇÕES DE LOGGING (MODO DESENVOLVIMENTO)
# ===============================================
logging.level.org.springframework.security.config.annotation.authentication.configuration=ERROR
logging.level.root=INFO
logging.level.br.com.gestaocondominio.api=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN

# ===============================================
# OTIMIZAÇÃO DE INICIALIZAÇÃO
# ===============================================
spring.main.lazy-initialization=true