# ===============================================
# CONFIGURAÇÃO DE BANCO DE DADOS PARA PRODUÇÃO (RENDER)
# ===============================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================================
# CONFIGURAÇÕES DO JPA/HIBERNATE
# ===============================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================================
# DESATIVA O FLYWAY PARA EVITAR ERRO DE LICENÇA
# ===============================================
spring.flyway.enabled=false
# ===============================================
# CONFIGURAÇÕES DE SEGURANÇA (JWT)
# ===============================================
api.security.jwt.secret-key=${API_SECURITY_JWT_SECRET_KEY}
api.security.jwt.expiration-time-ms=3600000

# ===============================================
# CONFIGURAÇÕES DE LOGGING (AJUSTADO PARA PRODUÇÃO)
# ===============================================
logging.level.org.springframework.security.config.annotation.authentication.configuration=ERROR
logging.level.root=WARN
logging.level.br.com.gestaocondominio.api=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR

# ===============================================
# OTIMIZAÇÃO DE INICIALIZAÇÃO
# ===============================================
spring.main.lazy-initialization=true